### ISSUE TITLE
Inconsistency when clicking on a problem's name in contest view vs round view

### ISSUE THREAD

**Issue by ghost** [varqox/sim#11]
When I open a contest and click on "Problems" then problem name it takes me to the pdf problem statement. When I click on the round name beforehand, however, it takes me to the problem's page (the page of a given problem in a given contest, not the general system-wide problem page).

**Comment by varqox** [comment]
The layout of the problems and rounds will be fundamentally changed soon, so it will no longer be an issue.

**Comment by varqox** [comment]
That future has come. It should be consistent now.
