### ISSUE TITLE
404 should be fixed quickly

### ISSUE THREAD

**Issue by tonowak** [varqox/sim#15]
"Fix contest submit error 404 after refresh" has certainly a **too low** priority in the _TODO_ list. When going back in history from submitting code, I get a 404 error. It is **extremely** annoying, because I'm often resubmitting code. Fix this _asap pls!!1!._

**Comment by varqox** [comment]
OK. I moved it to the top, should be done soon.

**Comment by varqox** [comment]
Fixed in dd136a9.
