### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by tonowak** [varqox/sim#16]
- [x] add Arch installation instructions (package names, needed step after pacman'ing mariadb)
- [x] correct Ubuntu package name: mariadb -> mysql
- [x] make -j 4 -> make -j $(nproc)
- [x] explain what should one write when "It will ask for MySQL credentials" (or at least write the default options)
- [x] change git clone command to clone develop branch
- [x] server.conf file -> sim.conf

**Comment by varqox** [comment]
- Ubuntu 18.04 has mariadb and Sim uses mariadb rather than mysql.
- Develop branch is a develop branch, master should be more stable, so it stays as is.
