### ISSUE TITLE
Web client broken on minor browsers due to a small compatibility issue

### ISSUE THREAD

**Issue by m4l352k4** [varqox/sim#20]
# TL;DR

Many minor distributions still use Chromium 83 but produced by the builder/optimizer `script.js` involves **logical nullish assignment** (??=) operator which is supported by Chromium 85 and above.

# A brief introduction of myself

With respect, gentleman. I am Adam Maleszka, a graduate of the ID class of the XIII'th High School in Szczecin. In the 7th grade I became a "laureate" of the Junior IT Olympics (_laureate_ in quotation marks, because that year the final did not quite take place). In practice, my fascination with computers reaches even the 1st grade though. I **love** competitive programming, networking, security and cryptography, GNU/Linux and the whole Open Source community.

# Chromium compatibility issue

I've been using Linux for five years and managed to choose my final Linux distribution, GNU Guix. It's ingenious, it's powerful, but also out-of-date a bit, especially with `qtwebengine` 5.15.2 (Chromium 83). It is worth noting that `qtwebengine` 5.15.2 is in many distributions, even on Debian Bullseye.

![image](https://user-images.githubusercontent.com/108515134/176872532-1e54d43d-8271-4fd6-81d8-4cffd624ae2c.png)

After inspecting the `script.js`, the reason seems to be in [logical nullish assignment operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment) which is not supported by Chromium 83:

![image](https://user-images.githubusercontent.com/108515134/176872618-ba56ab71-b0cb-486f-83ac-42f286a72110.png)

It is surprising to me, especially since the source code appears:

https://github.com/varqox/sim/blob/b115a4e858dda1288917243e511751b835c28482/src/web_server/static/kit/scripts.js#L238-L247

Does any compilation tool optimizes the above code for the newer standard, Chromium 85? It looks like a small tweak in the building system and SIM on my browser will work back.

**Comment by m4l352k4** [comment]
Additional info:
1. Web server was working with Chromium 83 half year ago. The issue started occuring near January.
2. After the building process `script.js` is the same (where do logical nullish assignment operators come from?)

**Comment by varqox** [comment]
Hello,

> # TL;DR
> 
> Many minor distributions still use Chromium 83 but produced by the builder/optimizer `script.js` involves **logical nullish assignment** (??=) operator which is supported by Chromium 85 and above.

I chose to upgrade requirements to chromium 85 because it is 22 months old and nowadays web browsers need to be updated frequently.

> # Chromium compatibility issue
> 
> I've been using Linux for five years and managed to choose my final Linux distribution, GNU Guix. It's ingenious, it's powerful, but also out-of-date a bit, especially with `qtwebengine` 5.15.2 (Chromium 83). It is worth noting that `qtwebengine` 5.15.2 is in many distributions, even on Debian Bullseye.

That's the problem with the `qtwebengine` packet - its quite out-of-date with current chromium version, and the old version of this packet in some distributions make it even worse, as you experience on your distribution.

> After inspecting the `script.js`, the reason seems to be in [logical nullish assignment operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment) which is not supported by Chromium 83:

Nice work, that is the culprit, but I cannot tell if there is some other js feature that is used and requires a never browser.

> Does any compilation tool optimizes the above code for the newer standard, Chromium 85? It looks like a small tweak in the building system and SIM on my browser will work back.

No, there is no compilation tool for JS. It is written all manually and the source version is what executes in the browser.

Overall, I do not want to switch back to support older browsers, because it is a burden and in a while the distributions will catch up. How long it will take? It is hard to tell. That is why non-rolling-release distributions for desktop is a frustrating choice. I recommend switching to the newer browser - you won't regret it.

**Comment by m4l352k4** [comment]
Hi, thank you for your quick reply.

> I recommend switching to the newer browser - you won't regret it.

Well, there are no major web browsers that are purely Open Source. I am a big proponent of the free software philosophy (see [FSF page](https://www.gnu.org/philosophy/free-sw.en.html)), and there aren't much that suit my needs. I've spent so many hours looking for an accurate browser, but there aren't a lot.

I don't want to spend too much time explaining why I don't like Chrome, Edge, Opera, Brave, Vivaldi, Safari, Tor, and all the remaining forks. I just need a lightweight, fully-keyboard-driven browser I can freely customize and know that it only does what I tell it and nothing more.

> That's the problem with the `qtwebengine` packet - its quite out-of-date with current chromium version, and the old version of this packet in some distributions make it even worse, as you experience on your distribution.

I agree that `qtwebengine` can sometimes be problematic, but on the whole there are no better alternatives in the Open Source world.

Firefox uses its own _Gecko_ engine. Gecko is fast, stable, and really pretty, but for now, very Firefox-specific. All of Gecko-based browsers are forks of Firefox (e.g. Waterfox, GNU's IceCat...), not including the Netscape project which is discontinued.

Apple Safari uses WebKit. There are only two WebKit implementations in the Open Source world: WebKitGTK and QtWebKit. The former is not much popular, with its leading browser [Epiphany](https://wiki.gnome.org/Apps/Web) (GNOME's default browser) --- it's feature-lacking and doesn't even support extensions. On the other hand, QtWebKit is not recommended due to known security issues, quoting the [QtWebKit release page](https://github.com/qtwebkit/qtwebkit/releases):

> WARNING: This release is based on old WebKit revision with known unpatched vulnerabilities. Please use it carefully and avoid visiting untrusted websites and using it for transmission of sensitive data.

Finally, the most popular layout engine is Chromium, whose the only implementation in the Open Source world is --- well --- `qtwebengine`. QtWebEngine is _really_ a core component of the Qt project. It occurs in all apps supporting any kind of HTML rendering. It also powers many browsers:

- [Falkon](https://www.falkon.org/) --- KDE web browser focused on privacy,
- [Qutebrowser](https://www.qutebrowser.org/) (mine) --- the most popular keyboard-focused browser,
- [VimB](https://fanglingsu.github.io/vimb/) --- the vim-like web browser,
- [Nyxt](https://nyxt.atlas.engineer/) --- recently popular emacs/vim-lik browser,

> Overall, I do not want to switch back to support older browsers, because it is a burden and in a while the distributions will catch up. How long it will take? It is hard to tell. That is why non-rolling-release distributions for desktop is a frustrating choice.

I completely agree that it is problematic to maintain compatibility with all distributions. On the other hand, in this case it doesn't seem like such a big mess to me. I mean, the cause of these compatibility issues does not seem to be the source code itself but something that modifies it. You said:

> No, there is no compilation tool for JS. It is written all manually and the source version is what executes in the browser.

But I don't think that the last sentence is true, because of this counter-example:

*In the source code:*

https://github.com/varqox/sim/blob/b115a4e858dda1288917243e511751b835c28482/src/web_server/static/kit/scripts.js#L238-L247

*Executed by the browser:*

![img](https://user-images.githubusercontent.com/108515134/176872618-ba56ab71-b0cb-486f-83ac-42f286a72110.png)

To summarise, I see the following solutions:

1. Wait for the `qtwebengine` package to be updated
2. Resign from beloved niche web browsers
3. Tweak a little _something_ that modifies the above code

If you feel that the last option is the least viable, I completely understand your decision.

Regards

**Comment by varqox** [comment]
> > No, there is no compilation tool for JS. It is written all manually and the source version is what executes in the browser.
> 
> But I don't think that the last sentence is true, because of this counter-example:
> 
> _In the source code:_
> 
> https://github.com/varqox/sim/blob/b115a4e858dda1288917243e511751b835c28482/src/web_server/static/kit/scripts.js#L238-L247
> 
> _Executed by the browser:_
> 
> ![img](https://user-images.githubusercontent.com/108515134/176872618-ba56ab71-b0cb-486f-83ac-42f286a72110.png)

You need to take into account that the version of SIM that you quote is different than the version you see running in the browser. The newest code is on the branch develop: https://github.com/varqox/sim/blob/develop/src/web_server/static/kit/scripts.js 

> To summarise, I see the following solutions:
> 
>     1. Wait for the `qtwebengine` package to be updated
> 
>     2. Resign from beloved niche web browsers
> 
>     3. Tweak a little _something_ that modifies the above code

There is NOTHING that modifies the code. I wrote the rules of the build system and the file is only copied - without any modifications: https://github.com/varqox/sim/blob/f8f6883901924292727ed4c97366801e67236052/meson.build#L257

**OFF-TOPIC:**
 
> I don't want to spend too much time explaining why I don't like Chrome, Edge, Opera, Brave, Vivaldi, Safari, Tor, and all the remaining forks. I just need a lightweight, fully-keyboard-driven browser I can freely customize and know that it only does what I tell it and nothing more.

> Firefox uses its own _Gecko_ engine. Gecko is fast, stable, and really pretty, but for now, very Firefox-specific. All of Gecko-based browsers are forks of Firefox (e.g. Waterfox, GNU's IceCat...), not including the Netscape project which is discontinued.

I use firefox and it works fine and fast, is open source and compliant with the w3c standards ;)

> Finally, the most popular layout engine is Chromium, whose the only implementation in the Open Source world is --- well --- `qtwebengine`. QtWebEngine is _really_ a core component of the Qt project. It occurs in all apps supporting any kind of HTML rendering. It also powers many browsers:

It looks to me, that `qtwebengine` uses chromium i.e. `qtwebengine` is built upon the [chromium](https://en.wikipedia.org/wiki/Chromium_(web_browser)) - a web browser, that uses the [Blink](https://en.wikipedia.org/wiki/Blink_(browser_engine)) web engine.

I do not intend to get into discussion about "who likes what the most", I just wanted make things more clear.

If you did not hear about it, you might like Linux-libre project that tries to get rid of proprietary binary blobs in the operating system kernel. There is also Libreboot that tries to do the same as the bootloader ;)

**Comment by m4l352k4** [comment]
> You need to take into account that the version of SIM that you quote is different than the version you see running in the browser. The newest code is on the branch develop: https://github.com/varqox/sim/blob/develop/src/web_server/static/kit/scripts.js

> There is NOTHING that modifies the code. I wrote the rules of the build system and the file is only copied - without any modifications:

Right, now I see. I would never have expected to use the development branch as a deployment branch --- this is usually what the master branch is for. But, never mind, you're the maintainer.

Some projects actually use JavaScript optimization tools. I simply wondered if the alleged optimizations were introduced consciously. However, as I see now, you have dropped support for Chromium 83 deliberately.

Well, I've introduced the browsers thread to make it clear that `qtwebengine` is an important component in the world of web browsers and worth considering when it comes to compatibility. However, I understand that you have made your decision consciously and are confident in it.

In the world of Open Source, it is sometimes difficult to find common ground. It is then better to follow a firm decision than to flare up over petty things.

You're the authority, you're the master.

**Comment by m4l352k4** [comment]
As a GNU Guix developer, I will try to find enough motivation and update the entire Qt package in the distribution.

Two years ago, I worked on the Neovim source code and wrote many extensions. A year ago I moved to Emacs, now I write under Emacs. I'm involved in the GNU project, I'm now developing GNU Guix. When it comes to experience in collaborative code writing, I think I can be trusted.

Should you need support, I am always willing to help with the SIM development. I have talked a lot with Michał Kuśmirek on what he would change in SIM. This platform has great potential, we all appreciate your work.

Now, this issue can be considered completely closed ;)
