### ISSUE TITLE
Teachers cannot edit their accounts

### ISSUE THREAD

**Issue by marximimus** [varqox/sim#21]
Every time I try to update my teacher account I get an error: 'type: Type selects option to which you do not have permission'. This error occurs even if I don't change anything.
![Screenshot 2022-10-25 at 20-04-15 User 419](https://user-images.githubusercontent.com/40419155/197848540-d2534bdd-fd9b-4f14-98e5-2ce475686874.png)

**Comment by varqox** [comment]
Fixed in 3b9557ac186c5a495be05dde22edfce2f49c645d, please upgrade sim
