### ISSUE TITLE
Installation hangs at running custom install script

### ISSUE THREAD

**Issue by Maritsu** [varqox/sim#22]
I've decided to try hosting a local instance of sim for whatever reason, and while installing I've been following the steps given in the README (steps from the section Instructions: release build and installation step by step).  
However, at step 7 (`meson install -C release-build`) the command shoots out a lot of output, then hangs with the last message being `Running custom install script '/usr/bin/sh -c <sim-install-dir>/release-build/setup-installation "$MESON_INSTALL_DESTDIR_PREFIX"'`. Is this step supposed to take >1 hour, or is something happening?
For information, everything before this happened went fine with zero errors whatsoever.

Running Arch Linux x86_64, with all required packages installed and updated.

**Comment by varqox** [comment]
Please update sim by using `git pull` and try again, it should be fixed now by 752b4e71ae0d2eeaf192ac21fc9c811fcd881e24.
