### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by XioR112** [varqox/sim#23]
Kroki do powtórzenia:
Wejść w zakładkę Problems, kliknąć View na jakimkolwiek zadaniu, wyjść z tego np. klikając X, a na koniec kliknąć w zakładkę All albo Public.

log:
Error: : undefined
Stack trace:
assert@https://sim.13lo.pl/kit/scripts.js?1674275080584771:3:9
resize_and_append@https://sim.13lo.pl/kit/scripts.js?1674275080584771:877:11
TabMenuBuilder/self.build_and_append_to/<@https://sim.13lo.pl/kit/scripts.js?1674275080584771:1354:41

**Comment by varqox** [comment]
Fixed in 984ea5521ce68fab0411346202daf854b6c03ef3
